export const GET_ALL_FILES = "GET_ALL_FILES";
export const GET_ALL_FILES_SUCCESS = "GET_ALL_FILES_SUCCESS";
export const GET_ALL_FILES_FAILED = "GET_ALL_FILES_FAILED";

export const FILE_UPLOAD = "FILE_UPLOAD";
export const FILE_UPLOAD_SUCCESS = "FILE_UPLOAD_SUCCESS";
export const FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED";

export const FILE_PROCESS = "FILE_PROCESS";
export const FILE_PROCESS_SUCCESS = "FILE_PROCESS_SUCCESS";
export const FILE_PROCESS_FAILED = "FILE_PROCESS_FAILED";