export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";

export const GET_ALL_CONTACTS_BY_AUTH_USER = "GET_ALL_CONTACTS_BY_AUTH_USER";
export const GET_ALL_CONTACTS_BY_AUTH_USER_SUCCESS = "GET_ALL_CONTACTS_BY_AUTH_USER_SUCCESS";
export const GET_ALL_CONTACTS_BY_AUTH_USER_FAILED = "GET_ALL_CONTACTS_BY_AUTH_USER_FAILED";

export const GET_FIELDS = "GET_FIELDS";
export const GET_FIELDS_SUCCESS = "GET_FIELDS_SUCCESS";
export const GET_FIELDS_FAILED = "GET_FIELDS_FAILED";